documentation:
- changed-files:
  - any-glob-to-any-file:
    - '*.md'
    - 'docs/**/*'
    - 'assets/**/*'

source:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/**/*'
      - '__tests__/**/*'

scripts:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - 'scripts/**/*'

ci/cd:
- all:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'